sudo: required
services:
  - docker

before_install:
  - docker build -t sarath2991/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarath2991/react-test npm test -- --coverage

after_success:
  - docker build -t sarath2991/multi-client ./client 
  - docker build -t sarath2991/multi-nginx ./nginx 
  - docker build -t sarath2991/multi-server ./server
  - docker build -t sarath2991/multi-worker ./worker
  
  #Login to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin 
  #Take those images and push them to docker hub
  - docker push sarath2991/multi-client
  - docker push sarath2991/multi-nginx
  - docker push sarath2991/multi-server
  - docker push sarath2991/multi-worker
